#!/bin/sh
### BEGIN INIT INFO
# Provides:          script-init
# Required-Start:    $network 
# Required-Stop:      
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts my GStreamer pipeline 
### END INIT INFO

case "$1" in
  start)
    /files/script.sh &
    ;;
  stop)
     pkill -f "/files/script.sh"
     ;;
  *)
    echo "Usage: /etc/init.d/script-init {start|stop}"
    exit 1
    ;;
esac

exit 0

